global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "node"
    dns_sd_configs:
      - names: ["node_exporter"]
        type: A
        port: 9100
  - job_name: "advisor"
    dns_sd_configs:
      - names: ["advisor"]
        type: A
        port: 8080
  - job_name: "press_release"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["192.168.96.6:8081"]
